### ISSUE TITLE
All data lost after update

### ISSUE THREAD

**Issue by itsmeshibintmz** [h4h13/paisa-app#10]
Morning updated to latest version from Play Store, all data lost showing an error "rendering error"![Screenshot_20241114-082121.png](https://github.com/user-attachments/assets/59d2c618-a8f8-4d91-9f35-34beb0a5346b)

**Comment by itsmeshibintmz** [comment]
@h4h13

**Comment by itsmeshibintmz** [comment]
Luckily i was able to restore from a backup I created yesterday. But it messed up all data. The total balance still counts an error value regardless of the excluded accounts, included accounts and all.

**Comment by itsmeshibintmz** [comment]
@h4h13 in the latest update Exclude account  is not working.

**Comment by thesixthsick** [comment]
Same. Last time i took a backup was November 01. All transactions between that got lost.

**Comment by itsmeshibintmz** [comment]
Hope you're working on the issues. Kindly do the needful @h4h13 .

**Comment by Dharmik48** [comment]
Same happened with me and unfortunately I didn't take any backup. So all data is lost.

> Hope you're working on the issues. Kindly do the needful @h4h13 .

And I don't think there will be any fix for lost data but there might be one for where even backed up data is not displayed correctly.

**Comment by itsmeshibintmz** [comment]
Closing this as no update is required on this.
