### ISSUE TITLE
Sub Transactions

### ISSUE THREAD

**Issue by ItzYeho** [h4h13/paisa-app#12]
It would be awesome if a transaction could have sub transactions for more granular view over your expenses and income.

For instance, you could have one transaction named "Group Food Order", and the main expense for it would be the payment to the restaurant, say, from account A. Then, you could add inside of that transaction incomes from your friends as "pay-back", from any account relevant. So for instance, 2 friends returned some money, one from account A and one from B, the whole transaction would be shown as the main expense, minus the two incomes, and only the delta would be shown in the overview.

This I believe would be an incredible feature to manage complex transactions that involve multiple accounts or multiple sub-transactions that would all be under the same roof for easier management.

**Comment by h4h13** [comment]
Hey, this seams like too much for work as you need to add people and split the bills maybe in feature, but I can't do it now

**Comment by h4h13** [comment]
Will close this for now thanks for the feedback
