### ISSUE TITLE
New Bug 🐛 - Font Not Loading

### ISSUE THREAD

**Issue by mrdarksidetm** [h4h13/paisa-app#13]
### **App Error Report**
--------------
Error: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/b667551a8e7d406c089cb2fdf754f2fddfb1dc256a33fcc06c690965c6b9d5d7.ttf: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = fonts.gstatic.com, port = 44880, uri=https://fonts.gstatic.com/s/a/b667551a8e7d406c089cb2fdf754f2fddfb1dc256a33fcc06c690965c6b9d5d7.ttf

Stack Trace:
#0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:261)
<asynchronous suspension>
#1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:178)
<asynchronous suspension>
#2      googleFontsTextStyle.<anonymous closure> (package:google_fonts/src/google_fonts_base.dart:115)
<asynchronous suspension>

Device Info:
App Version: 7.2.0
Build Number: 720

![Screenshot_20241120_204853](https://github.com/user-attachments/assets/0d69399b-8d25-4de2-a5af-4b43412a4db9)

**Comment by h4h13** [comment]
Hi are you suing app without internet

**Comment by h4h13** [comment]
#15 closing this also
