### ISSUE TITLE
App Error Report

### ISSUE THREAD

**Issue by mrdarksidetm** [h4h13/paisa-app#14]
App Error Report
--------------
Error: Bad state: Cannot emit new states after calling close

Stack Trace:
#0      BlocBase.emit (package:bloc/src/bloc_base.dart:97)
#1      TransactionUpdateCubitV2.addTransaction.<anonymous closure>.<anonymous closure> (package:paisa/features/transaction/presentation/cubit/transaction_update_cubit_v2.dart:114)
#2      Right.fold (package:dartz/src/either.dart:200)
#3      TransactionUpdateCubitV2.addTransaction.<anonymous closure> (package:paisa/features/transaction/presentation/cubit/transaction_update_cubit_v2.dart:110)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861)
#5      Future._propagateToListeners (dart:async/future_impl.dart:890)
#6      Future._completeWithValue (dart:async/future_impl.dart:666)
<asynchronous suspension>

Device Info:
App Version: 7.2.0
Build Number: 7.2.0

**Comment by h4h13** [comment]
Let me know if this issue persists
