### ISSUE TITLE
Font loading must not be cknsidered as error.

### ISSUE THREAD

**Issue by vjdyofficial** [h4h13/paisa-app#15]
App Error Report
--------------
Error: Exception: GoogleFonts.config.allowRuntimeFetching is false but font MySoul-Regular was not found in the application assets. Ensure MySoul-Regular.ttf exists in a folder that is included in your pubspec's assets.

Stack Trace:
#0      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:182)
<asynchronous suspension>
#1      googleFontsTextStyle.<anonymous closure> (package:google_fonts/src/google_fonts_base.dart:115)
<asynchronous suspension>

Device Info:
App Version: 7.2.1
Build Number: 721

**Comment by h4h13** [comment]
The fonts are always downloading while using the app from Google
Fonts, if you're using app without internet it might cause the problem

**Comment by h4h13** [comment]
I have removed the fonts chooser for the app causing app size inscreases to 300MB+ and causing the app load slower
