### ISSUE TITLE
App crashing frequently

### ISSUE THREAD

**Issue by itsmeshibintmz** [h4h13/paisa-app#16]
![Screenshot_20241130-125728.png](https://github.com/user-attachments/assets/b08f9c6d-0d49-4bdc-b7de-102e7f91a369)

App crashing unexpectedly with this message and similar messages. This happened when I opened font style in settings.

**Comment by itsmeshibintmz** [comment]
@h4h13 not even able to add a transaction.![Screenshot_20241130-171342.png](https://github.com/user-attachments/assets/9ea5e351-423c-44d4-9616-b85f549d1192)

Getting so many crash notifications here and there.

**Comment by itsmeshibintmz** [comment]
App Error Report
--------------
Error: type 'Null' is not a subtype of type 'TransactionUpdateCubitV2' in type cast

Stack Trace:
#0      _CreateInheritedProviderState.dispose (package:provider/src/inherited_provider.dart:797)
#1      _InheritedProviderScopeElement.unmount (package:provider/src/inherited_provider.dart:559)
#2      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077)
#3      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#4      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#7      RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#10     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#13     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#16     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#19     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#22     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#25     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#28     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#34     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#43     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#49     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#55     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#58     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#61     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#64     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#67     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#70     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#73     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#76     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#79     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#82     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#85     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#88     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#91     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#94     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#97     RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#100    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#103    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#106    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#109    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#112    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#115    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#118    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#121    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#124    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#127    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#130    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#133    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#136    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#139    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#142    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#145    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6998)
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#148    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#151    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#154    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#155    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#156    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#157    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#158    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#159    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#160    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#161    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#162    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#163    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#164    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#165    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#166    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#167    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#168    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#169    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#170    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#171    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#172    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886)
#173    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#174    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#175    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#176    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#177    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#178    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#179    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#180    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#181    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#182    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#183    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#184    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#185    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#186    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#187    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#188    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#189    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#190    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#191    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#192    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#193    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#194    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#195    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#196    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#197    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#198    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#199    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#200    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#201    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#202    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#203    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#204    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#205    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#206    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#207    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#208    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#209    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#210    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#211    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#212    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073)
#213    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075)
#214    RootElement.visitChildren (package:flutter/src/widgets/binding.dart:1559)
#215    _InactiveElements._unmount (package:flutter/src/widgets/framew

**Comment by h4h13** [comment]
This bug got solved can you share app version are you using
