### ISSUE TITLE
App don't open.

### ISSUE THREAD

**Issue by Pedro7Santana** [h4h13/paisa-app#4]
The transfers between accounts don't work. I made the transfer, that appear in the home section, but don't appear in the respective account. The account who send, and the account who receive, both don't change the values. I'm a Android user, and use the Play Store app.

**Comment by Pedro7Santana** [comment]
Now, after the last update, the transfer in general don't work. When I try to insert a transfer, that need a name, or description. But don't have how to insert that in a transfer.

**Comment by Pedro7Santana** [comment]
Today, I update Paisa app from Google Play Store in my Android 11, and the app doesn't open anymore. Just stay in a white screen, and don't load or show any information. I subscribe the Beta Tester Program, but I don't if the last update are closed (beta) or public. The version is 7.0.9

**Comment by h4h13** [comment]
@Pedro7Santana Hey, is this still happening ?

**Comment by Pedro7Santana** [comment]
Don't worry, this issue was fixed in the last updates.
