### ISSUE TITLE
Not able to select existing category for new expense

### ISSUE THREAD

**Issue by itsmeshibintmz** [h4h13/paisa-app#6]
I've used this app in the past. Now today I installed it again. One issue I face is I cannot select any category for a new expense. It's showing an option to create a new category, but I'm able to use existing categories in the income section. Attaching screenshots for reference![Screenshot_20241025-205349.png](https://github.com/user-attachments/assets/e7b489c1-d352-4a5e-a132-92da18f129c3)

![Screenshot_20241025-205344.png](https://github.com/user-attachments/assets/d8f5afd6-cb63-4b72-a131-e257257f5672)

**Comment by itsmeshibintmz** [comment]
Hi @h4h13

**Comment by h4h13** [comment]
Hey, in the new update you'll have separate categories like income and expenses so you have to make them or update the existing ones

**Comment by itsmeshibintmz** [comment]
Oh okay if that's the case, okay got it. Thanks for the reply.
