### ISSUE TITLE
Can't Open the app on Android 14 (#6.7.0)

### ISSUE THREAD

**Issue by AlexxyQQ** [h4h13/paisa-app#7]
I am currently on Android 14 October Security Patch. 

I can't open the after installation. Getting this message

![Screenshot_20241028-102421](https://github.com/user-attachments/assets/ea6f873a-0ad4-4e31-bdd8-128015a3bcb8)

**Comment by h4h13** [comment]
Hey, let me know if this is still happening in latest version
