### ISSUE TITLE
Not able to transfer from one account to another 

### ISSUE THREAD

**Issue by itsmeshibintmz** [h4h13/paisa-app#8]
As title says, not able to transfer amount from one account to another, showing "Enter transaction name or select a category" in which category selection is possible and is done, but no option to enter transaction name. Added transfer amount, selected category, selected from and to. Shows the popup at bottom @h4h13 .

**Comment by itsmeshibintmz** [comment]
@h4h13

**Comment by h4h13** [comment]
This is fixed in the new version

**Comment by itsmeshibintmz** [comment]
Thanks, may i know when the update is coming in Play Store/GitHub? 🙂

**Comment by h4h13** [comment]
I'm still under completing the budget once that's done it will be there everywhere

**Comment by itsmeshibintmz** [comment]
Thanks.

**Comment by h4h13** [comment]
Will close this issue for now

**Comment by itsmeshibintmz** [comment]
I'll check the latest update and update here the results.
