### ISSUE TITLE
No account update in Account section 

### ISSUE THREAD

**Issue by itsmeshibintmz** [h4h13/paisa-app#9]
Whenever a transaction whether it is income or expense is added to an account, it's not updating in the accounts section. It still shows the first added amount in the accounts section.

**Comment by itsmeshibintmz** [comment]
@h4h13

**Comment by h4h13** [comment]
What if we reopen the app

**Comment by itsmeshibintmz** [comment]
It's same. I'm daily using this application.

**Comment by h4h13** [comment]
Can you record a video or something

**Comment by itsmeshibintmz** [comment]
Sure will try to do today itself.

**Comment by itsmeshibintmz** [comment]
Hi, can you try this, steps I can explain
1: add an account with an amount
2: do an income or expense for the account
3: check if the amount of account is changed or not

(Sorry for not sharing a video)

**Comment by itsmeshibintmz** [comment]
hope in the new update this doesn't mess up the amount section in the app(like currently it's not updated rt, but I count transactions, so when starts working, it doesn't mess up past activities done)

**Comment by itsmeshibintmz** [comment]
I daily use this application for tracking my expenses. If the testing apks doesn't affect much of the basic functionalities, I can do the internal testing, I'm happy to help. Please let me know.

**Comment by h4h13** [comment]
Is it still happening

**Comment by itsmeshibintmz** [comment]
I've removed the app as from last update I did earlier messed up the data. Lost all data. So now I need to check again by installing new version.
